# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install MySQL
    # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    init: |
      sudo apt-get update
      sudo apt-get install mysql-server -y
      gp sync-done installation 

  - name: MySQL
    init: gp sync-await installation
    command: |
      cd ./snippetbox; sudo cp my.cnf /etc/mysql; sudo mysql;

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 4000 for the frontend
    port: 4000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
